CREATE TABLE device
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name           VARCHAR(50) NOT NULL,
    brand          VARCHAR(50) NOT NULL,
    state          VARCHAR(50) NOT NULL,
    creation_date  DATE        NOT NULL
);