networks:
  global_network:
    driver: bridge

services:
  db:
    image: postgres:17-alpine
    container_name: global-db
    env_file:
      - ./postgres.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - global_network
    restart: always

  api:
    image: maven:3.9.6-eclipse-temurin-21
    container_name: global-api
    working_dir: /app
    env_file:
      - ./api.env
    ports:
      - "8080:8080"
    volumes:
      - ../api:/app
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - global_network
    restart: on-failure

  adminer:
    image: adminer:4.8.1-standalone
    container_name: global-adminer
    ports:
      - "8081:8080"
    depends_on:
      - db
    networks:
      - global_network
    restart: always

volumes:
  db_data:
    driver: local